# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
   name = "Venue"
   pageRef = "venue"
   weight = 9
   identifier = 'venue'

[[main]]
   name = "Conference Information"
   pageRef = "conference_information"
   weight = 10
   identifier = 'conference_information'

[[main]]
   name = "Community Events"
   pageRef = "community_events"
   weight = 12
   identifier = 'community_events'
   parent = 'conference_information'

[[main]]
   name = "Call for Participation"
   pageRef = "cfp"
   weight = 11
   identifier = 'cfp'

[[main]]
   name = "Call for Posters"
   pageRef = "call_for_posters"
   weight = 12
   identifier = 'cfposters'
   parent = 'cfp'

[[main]]
   name = "Call for Doctoral Consortium Participation"
   pageRef = "call_for_doctoral_consortium"
   weight = 13
   identifier = 'cfdc'
   parent = 'cfp'

[[main]]
   name = "Committees"
   pageRef = "committees"
   weight = 20
   identifier = 'committees'

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

# [[main]]
#  identifier = "locale"
#  weight = 100
#  [main.params]
#    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
   name = "Past Conferences"
   pageRef = "past_conferences"
   weight = 10

[[footer]]
   name = "Historical Conference Awards"
   pageRef = "past_awards"
   weight = 20

[[footer]]
   name = "EAAMO at a Glance"
   pageRef = "eaamo_at_a_glance_24"
   weight = 30

[[footer]]
   name = "Become a Sponsor"
   pageRef = "become_a_sponsor"
   weight = 40

[[footer]]
   name = "Get Involved"
   pageRef = "get_involved"
   weight = 50

[[footer]]
   name = "Policies"
   pageRef = "policies"
   weight = 60